//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centauro.DigitalInvoice.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string accountId { get; set; }
        public string userATV { get; set; }
        public string passwordATV { get; set; }
        public string certificateName { get; set; }
        public int certificatePIN { get; set; }
        public string certificateExt { get; set; }
        public string certificate { get; set; }
        public bool enabled { get; set; }
    }
}
