//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centauro.DigitalInvoice.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallBackReceived
    {
        public string IdCallBack { get; set; }
        public string fecha { get; set; }
        public string clave { get; set; }
        public string indEstado { get; set; }
        public string callBackUrl { get; set; }
        public string respuestaXml { get; set; }
        public System.DateTime fechaCallBack { get; set; }
    }
}
