//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centauro.DigitalInvoice.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalInvoiceEntities : DbContext
    {
        public DigitalInvoiceEntities()
            : base("name=DigitalInvoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeProductService> CodeProductService { get; set; }
        public virtual DbSet<DocumentTypeAuthExon> DocumentTypeAuthExon { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
        public virtual DbSet<SaleCondition> SaleCondition { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<MeasureUnit> MeasureUnit { get; set; }
        public virtual DbSet<Taxes> Taxes { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<CallBackReceived> CallBackReceived { get; set; }
        public virtual DbSet<LogRequest> LogRequest { get; set; }
        public virtual DbSet<IdentificationType> IdentificationType { get; set; }
        public virtual DbSet<RequestRecord> RequestRecord { get; set; }
    }
}
