//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centauro.DigitalInvoice.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleCondition
    {
        public int CodeId { get; set; }
        public string SaleCondition1 { get; set; }
    }
}
